# Generated by Django 4.0.5 on 2024-10-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='out_of_storage_sizes',
        ),
    ]
