# Generated by Django 4.0.5 on 2024-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sizes_product_cart_product_wish_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default-image.jpg', upload_to='products/'),
        ),
    ]
