import localFont from "next/font/local";
import "./globals.css";

const josefinSans = localFont({
  src: "./fonts/JosefinSans-VariableFont_wght.ttf",
  variable: "--font-josefin",
  weight: "100 900",
});

export const metadata = {
  title: "FakeStore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${josefinSans.variable}`} 
      >
        {children}
      </body>
    </html>
  );
}
